# Identifiants SonarCloud
sonar.projectKey=EZRA2001-rgb_smart-maintenance-quality
sonar.organization=EZRA2001-rgb
sonar.host.url=https://sonarcloud.io

sonar.projectName=smart-maintenance-quality
sonar.projectVersion=2.0.0


# Sources à analyser
sonar.sources=src
sonar.tests=src/__tests__

# Rapports de couverture
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js
sonar.test.exclusions=**/__tests__/**

# Encoding et règles
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.javascript.maxLinesPerFunction=30
